### ISSUE TITLE
How can I customize this theme?

### ISSUE THREAD

**Issue by TwangyMoney** [DevEvil99/Azurite-Discord-Theme#1]
I didn't see any options for customization. Are we supposed to just edit the code? I needed to know how I could actually customize. How is it customizable? I don't see any options to customize.

**Comment by DevEvil99** [comment]
Click the edit button and change variables value then save it

**Comment by TwangyMoney** [comment]
Sir I see no edit button. Where is it.

**Comment by TwangyMoney** [comment]
Or do you mean the script edit button

**Comment by DevEvil99** [comment]
Pencil icon in theme section

**Comment by TwangyMoney** [comment]
But that just lets me change the background image

**Comment by DevEvil99** [comment]
No

**Comment by TwangyMoney** [comment]
The colors too? Okay what about this. How can I edit the value that edits the Discord text top left?

**Comment by DevEvil99** [comment]
You can ONLY change:
Background 
Home icon
Colors

**Comment by TwangyMoney** [comment]
Yeah, I understood that. But is there like any way at all for me to change the text top left? Maybe from the source code? Oh, and how do I change the home icon?

**Comment by DevEvil99** [comment]
No.
For homeicon change --darkplus-homeicon value

**Comment by TwangyMoney** [comment]
Okay then, understood. Thanks. Now I have a different problem not sure if I should make another issue or not. But it's like whenever I enable this theme none of my messages load. When I disable it, the messages load again. At first this didn't happen but it's happening suddenly. I didn't edit anything yet.

**Comment by DevEvil99** [comment]
I know, im working on it, no ETA

**Comment by TwangyMoney** [comment]
Oh. Okay if a fix is released how would I know?

**Comment by DevEvil99** [comment]
discord server, announcement channel

**Comment by TwangyMoney** [comment]
Nice. Imma close this issue then. Thank you for your time.

**Comment by DevEvil99** [comment]
> Okay then, understood. Thanks. Now I have a different problem not sure if I should make another issue or not. But it's like whenever I enable this theme none of my messages load. When I disable it, the messages load again. At first this didn't happen but it's happening suddenly. I didn't edit anything yet.

fixed
