### ISSUE TITLE
I cannot see any messages [Fixed] | Scrolling bug 

### ISSUE THREAD

**Issue by dianallar** [DevEvil99/Azurite-Discord-Theme#2]
whenever I go into a text channel or DM, I am unable to see any messages. what is the fix for this?

**Comment by DevEvil99** [comment]
fixed

**Comment by dianallar** [comment]
Hi, I'm sorry to bother you again...
I also cannot scroll down in chat channels or DMs.

**Comment by DevEvil99** [comment]
Can you give me more details, like video or something

**Comment by dianallar** [comment]
> Can you give me more details, like video or something

ok one second

**Comment by dianallar** [comment]
> > Can you give me more details, like video or something
> 
> ok one second

https://user-images.githubusercontent.com/118851223/215290007-4af4bc23-e1fa-435b-bf77-26c103bcf6a8.mp4

**Comment by DevEvil99** [comment]
Thank you, I will fix it

**Comment by dianallar** [comment]
no problem

**Comment by DevEvil99** [comment]
can you use your mouse cursor to scroll?

**Comment by dianallar** [comment]
no, I cannot
(sorry for the late response)

**Comment by DevEvil99** [comment]
hmmm, ok I'll fix it but I have a lot of projects at the moment so it will take a while

**Comment by DevEvil99** [comment]
hello, its fixed!

**Comment by dianallar** [comment]
thank you!!!!
