### ISSUE TITLE
Missing fields in theme

### ISSUE THREAD

**Issue by whataboutism-alos** [DevEvil99/Azurite-Discord-Theme#4]
A discord update at some point has broken certain elements of this theme. This is an excellent theme, btw.

`images redacted`

**Comment by DevEvil99** [comment]
Except for the second one, all the others were never styled, and I don’t currently have plans to style them. Additionally, I don't style the BD settings and any parts that a plugin might add or modify

**Comment by whataboutism-alos** [comment]
> Except for the second one, all the others were never styled, and I don’t currently have plans to style them. Additionally, I don't style the BD settings and any parts that a plugin might add or modify

Gotcha, thanks for the reply so soon.
